Adding slurm-gcp-v5-centos7 to integration tests.
This IS CURRENTLY broken as the login node seems unreachable after the
cluster is deployed. More investigation is needed.

In addition to adding the required files and changes for the integration
tests, this commig contains:
- fixes to the public examples where the login
nodes associated with Slurm v5 did not mount /home
- improvements to slurm and base-integration-tests, adding retries to
  "instances_list".
- improved messages during the slurm integration tests
- create_deployment.sh now uploads the deployment folder to the same
  folder as the backend state on GCS. This allow quickly recovering,
  tearing down or reproducing a build deployment.

diff --git a/tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml b/tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
--- a/tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
+++ b/tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
@@ -43,6 +43,10 @@
       NETWORK: "{{ network }}"
     args:
       creates: "{{ workspace }}/{{ deployment_name }}.tgz"
+    register: create_output
+  - name: Print ghpc blueprint information
+    ansible.builtin.debug:
+      var: create_output.stdout_lines
   - name: Create Infrastructure and test
     block:
     - name: Create Cluster with Terraform
@@ -60,6 +64,9 @@
       changed_when: false
       delegate_to: localhost
       register: instances_list
+      retries: 2
+      delay: 60
+      until: instances_list.rc == 0
       command: >-
         gcloud compute instances list
         --filter="labels.ghpc_deployment={{ deployment_name }}"
@@ -67,18 +74,31 @@
     - name: Print instance information
       ansible.builtin.debug:
         var: instances_list.stdout_lines
-    - name: Get login IP
+    - name: Get first login node IP
       changed_when: false
       register: login_ip
-      command: >-
-        gcloud compute instances describe --zone={{ zone }} {{ login_node }}
-        --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
+      shell: |
+        set -e
+        LOGIN_NODES=$(gcloud compute instances list --zones={{ zone }} --filter="name ~ {{ login_node }}" --format='value(name)')
+        for login in $LOGIN_NODES
+        do
+          gcloud compute instances describe --zone={{ zone }} $login --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
+          exit 0
+        done
+        echo "Login Node IP not found. List of login nodes: [$LOGIN_NODES]"
+        exit 1
+    - name: Print login public IP
+      ansible.builtin.debug:
+        var: login_ip.stdout_lines
     - name: Get Controller IP
       changed_when: false
       register: controller_ip
       command: >-
         gcloud compute instances describe --zone={{ zone }} {{ controller_node }}
         --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
+    - name: Print Controller public IP
+      ansible.builtin.debug:
+        var: controller_ip.stdout_lines
 
     ## Setup firewall for cloud build
     - name: Get Builder IP
