Refactor kueue daily tests to use shared Kueue pod cleanup script

diff --git a/tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml b/tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml
--- a/tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml
+++ b/tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml
@@ -129,15 +129,7 @@ steps:
             command: ["/bin/bash", "-c"]
             args:
             - |
-              set -e -u -o pipefail
-              echo "\"test_file_path\": tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml"
-              echo "Sourcing find_available_zone.sh to determine zone."
-              source /workspace/tools/cloud-build/wait_for_available_zone.sh
-              if [ -z "\$${ZONE:-}" ]; then
-                echo "ERROR: ZONE not found" >&2
-                exit 1
-              fi
-              set -x
+              set -x -e
               echo "\"test_file_path\": tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml"
               cd /workspace
 
@@ -151,6 +143,15 @@ steps:
               source /workspace/tools/cloud-build/kueue_cleanup_pod.sh
               trap cleanup_pod EXIT SIGTERM SIGINT
 
+              set -e -u -o pipefail
+              echo "\"test_file_path\": tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml"
+              echo "Sourcing find_available_zone.sh to determine zone."
+              source /workspace/tools/cloud-build/wait_for_available_zone.sh
+              if [ -z "\$${ZONE:-}" ]; then
+                echo "ERROR: ZONE not found" >&2
+                exit 1
+              fi
+              set -x
               bash tools/get_binary.sh "${_TEST_PREFIX}"
               REGION="\$${ZONE%-*}"
               BUILD_ID_SHORT="\$${BUILD_ID:0:6}"
@@ -240,7 +241,6 @@ steps:
       wait $$MONITOR_PID
       EXIT_CODE=$$?
       set -e
-      echo "\"test_file_path\": tools/cloud-build/daily-tests/builds/ml-g4-onspot-slurm.yaml"
 
       if [ $$EXIT_CODE -eq 0 ]; then
         echo "Job succeeded!"
